name: epiwrite
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.13.1
  - scikit-learn=1.5.2
  - statsmodels=0.14.3
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - plotly=5.24.1
  - biopython=1.84
  - pyranges=0.3.10
  - tqdm=4.66.4
  - joblib=1.4.2
  - pyyaml=6.0.2
  - openpyxl=3.1.5
  - tabulate=0.9.0
  - rpy2=3.5.16
  - r-base=4.3.3
  - bioconductor-deseq2=1.42.0
  - jupyterlab=4.2.5
  - nb_conda_kernels=2.3.1
  - pip
  - pip:
      - google-colab==1.0.0
      - gcsfs==2025.1.0

